version: '3.8'

services:
  postgres:
    container_name: postgres_database
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_db:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    env_file:
      - .env

volumes:
  postgres_db:
